### ISSUE TITLE
"terraform apply" during IKS cluster creation returns garbage error

### ISSUE THREAD

**Issue by bradbehle** [IBM-Cloud/terraform-provider-ibm#535] opened 2019-03-19 20:09 UTC
### Terraform Version
```
brads-macbook:terraform behle$ terraform -v
Terraform v0.11.13
+ provider.ibm v0.14.1 - NOTE: this is a special provider with service endpoint support
+ provider.null v2.1.0
```

### Affected Resource(s)
ibm_container_cluster.cluster

### Debug Output
By the time I enabled logging, the problem couldn't be reproduced.  I think the error only shows up if the cluster is created, then an error occurs getting its status.  Re-running terraform apply will give an error until the cluster is in `pending` state.

### Expected Behavior
terraform apply should not have produced an indecipherable error

### Actual Behavior
The cluster was created (I can see the cluster now in my account, it looks fine), but soon after the "create" api was called, as terraform must have been getting status, I got the error, which can be seen here: https://gist.github.com/bradbehle/3b41bd2b272a74718cda804364279626

This error occurred when ever I called terraform apply, until the cluster went to "pending" state, then the error went away and terraform apply would show me the state of my resources and again ask if I wanted to apply this.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Watch it create the cluster, and then get the error in the gist above
3. Can repeatedly call `terraform apply`, it will continue to fail until the cluster gets to "pending" state

### Important Factoids
I'm using a custom built IBM Provider that has support for private service endpoints.

### References
None

**Comment by AlexandrSemak** [comment] 2019-03-21 09:55
We also faced with this issue, Terraform is getting every time now:

`ibm_container_cluster.cluster: Error waiting for cluster (fc31c1ba4992463db5f9a082944230c9) to become ready: Error retrieving cluster: Request failed with status code: 503`

`ibm_container_cluster.cluster: ibm_container_cluster.cluster: Error communicating with the API: Request failed with status code: 503`

but even got this error cluster continue provision in account.

**Comment by jmgalvez** [comment] 2019-03-21 10:42
```
Terraform v0.11.13
+ provider.helm 0.9.0
+ provider.ibm v0.15.0
+ provider.kubernetes v1.5.2

```

Same issue here.


`[2019-03-21T09:06:19.096Z] Error: Error applying plan:
[2019-03-21T09:06:19.096Z] * module.creation.ibm_container_cluster.k8s: 1 error(s) occurred:
[2019-03-21T09:06:19.096Z] * ibm_container_cluster.k8s: Error waiting for cluster (784e8e1b5e76485b8cf72882e870f3ff) to become ready: Error retrieving cluster: Request failed with status code: 503, ServerErrorResponse: ����
[2019-03-21T09:06:19.096Z] �@�����\�F��VEV���$.��c��	��{	�n9����U��s��f��� !*K�7/�k�v�r���q��2���"<��@�����������a��#E�K�[����&���-F��{9��>`����5��P}y�O?�"!���_N�4`��{7�>_����
`

**Comment by Praveengostu** [comment] 2019-03-22 09:06
The issue occurs once the cluster is provisioned and waits for the cluster state to become normal. During the wait the ibm cluster resource polls for the status of the cluster and the get reutrns with an 503 error.

**Comment by Praveengostu** [comment] 2019-03-22 10:24
The issue is fixed and available in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.15.1

**Comment by AlexandrSemak** [comment] 2019-03-22 10:25
> The issue is fixed and available in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.15.1

Thank you a lot

**Comment by jmgalvez** [comment] 2019-03-22 10:53
> The issue is fixed and available in latest release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.15.1

Thank you very much!

**Comment by Praveengostu** [comment] 2019-04-25 04:04
Closing this issue as it is fixed with release https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.15.1. Pls reopen it was able to recreated with later versions

**Closed by Praveengostu** 2019-04-25 04:04 UTC
