### ISSUE TITLE
ibm_dns_record cannot set "@" TTL

### ISSUE THREAD

**Issue by aaronmcohen** [IBM-Cloud/terraform-provider-ibm#380] opened 2018-10-01 19:43 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

terraform -v
```
Terraform v0.11.8
+ provider.ibm (unversioned)
+ provider.null v1.0.0
+ provider.random v2.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0
```

### Affected Resource(s)

- ibm_dns_domain
- ibm_dns_record

### Terraform Configuration Files
```hcl
resource "ibm_dns_domain" "subdomainzone" {
  name = "test.ibmcsf.net"
  target = "10.0.0.0"
}

resource "ibm_dns_record" "subdomain_at_sign" {
  data               =  "10.0.0.0"
  domain_id          = "${ibm_dns_domain.subdomainzone.id}"
  host               = "@"
  responsible_person = "noreply@us.ibm.com"
  ttl                = 900
  type               = "a"
}```

### Expected Behavior
The dns entry ttl for "@" should be 900 ms.

### Actual Behavior
The dns entry ttl for "@" is 86400 ms.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by hkantare** [comment] 2018-10-09 09:51
We are not able to reproduce the issue. When you create "ibm_dns_name" by default a record of Type 'A' will get added with ttl of 86400ms. When you try to create another record "ibm_dns_record" it gets created successfully with ttl 900ms
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/24930306/46661496-f3e34d80-cbd6-11e8-8a78-00e9eee7d633.png">

**Comment by hkantare** [comment] 2019-07-01 06:00
closing the issue..

**Closed by hkantare** 2019-07-01 06:00 UTC
