### ISSUE TITLE
[EN] Error when creating EN resource instance

### ISSUE THREAD

**Issue by Ak-sky** [IBM-Cloud/terraform-provider-ibm#5489] opened 2024-07-05 05:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

Terraform Version v1.5.7
Terraform IBM Provider Version v1.56.1

### Affected Resource(s)

* ibm_resource_instance

### Terraform Configuration Files

When this EN [test](https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/tree/main/examples/basic) was runnning in our pipeline during continuous testing we noticed that test failed when creating EN resource.

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output

```
" tf_provider_addr=provider tf_req_id=1fa797a5-fdfe-b3f2-1c5c-e34882fa1111 tf_resource_type=ibm_resource_instance tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_detail="---
id: terraform-446cc00a
summary: |
  [ERROR] Error when creating resource instance: An error occurred getting the supported service broker for the plan id: 79abfa41-d235-4f66-b7c0-bd9454b7765d. Error: Failed to retrieve broker: crn:v1:bluemix:public:resource-controller::a/5da31b8b1e304946965daf6db1a52e9e::resource-broker:cc5a32ee-b764-41ac-91df-065938fb62ad with resp code: {
      "StatusCode": 500,
      "Headers": {
```

TF Trace Logs - [trace.log](https://github.com/user-attachments/files/16105160/trace.log)
TF Apply stdout - [stdout.txt](https://github.com/user-attachments/files/16105161/stdout.txt)

### Expected Behavior

EN resource should have been created without any issue.

### Actual Behavior

Error during EN resource creation.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Divya-Singh1693** [comment] 2024-07-08 04:58
@Ak-sky I suppose you are seeing failure while creating Event Notifications instance in `eu-de` region. Please confirm.

I have tried creating instance and i was able to provision it successfully. The failure might be on resource controller side at the moment.  The provisioning and de-provisioning happens from resource controller. If the issue is still happening please let me know.
<img width="1069" alt="Screenshot 2024-07-08 at 10 27 14 AM" src="https://github.com/IBM-Cloud/terraform-provider-ibm/assets/68578534/5ff50ed3-2c9d-46f3-bdeb-f93f8e78ece4">

**Comment by Divya-Singh1693** [comment] 2024-07-09 04:05
@Ak-sky It might be on the resource controller side since resource provisioning is a resource controller request.

**Comment by Divya-Singh1693** [comment] 2024-08-01 04:17
@Ak-sky Can we close this issue, if there is no issue observed further.

**Closed** 2024-08-01 05:18 UTC
Labels: service/Resource Management
