### ISSUE TITLE
ibm_account / ibmcloud iam accounts problem ? 

### ISSUE THREAD

**Issue by grazius** [IBM-Cloud/terraform-provider-ibm#671] opened 2019-08-02 14:46 UTC
Hi there,

I just try to get data on account to consume ibm_container_cluster.

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
ibm_account

### Terraform Configuration Files
```hcl
data "ibm_org" "org" {
  org = "${var.organisation}"
}
data "ibm_account" "account" {
  org_guid = "${data.ibm_org.org.id}"
}
```

### Debug Output
we don't have access to gist in my company
```
* data.ibm_account.account: data.ibm_account.account: Error retrieving users in account: Request failed with status code: 403, ServerErrorResponse: {"errors":[{"code":9999,"message":"Current user does not have access to team directory.","more_info":""}]}
```

### The Problem
`ibmcloud iam accounts` display accounts of my organisation properly
so i have access to this resource !?

**Comment by mzmudziak** [comment] 2019-10-02 09:57
We are having the same problem, with the following configuration:
```hcl
provider "ibm" {
  region = "${var.region}"
}

data "ibm_org" "org" {
  org = "${var.org}"
}

data "ibm_account" "account" {
  org_guid = "${data.ibm_org.org.id}"
}
```

The error message:
```* data.ibm_account.account: data.ibm_account.account: Error retrieving users in account: Request failed with status code: 403, ServerErrorResponse: {"errors":[{"code":9999,"message":"Current user does not have access to team directory.","more_info":""}]}
```

I'd be interested to know what this error message means and how can it be solved. It has worked before, and our configuration has not changed much.

**Comment by mzmudziak** [comment] 2019-10-02 10:23
I have reproduced this issue using the IBM Cloud REST API, and found a possible workaround to get it fixed... ?

1. Generate an IAM access_token:
```bash
$ curl -k -X POST \
  --header "Content-Type: application/x-www-form-urlencoded" \
  --header "Accept: application/json" \
  --data-urlencode "grant_type=urn:ibm:params:oauth:grant-type:apikey" \
  --data-urlencode "apikey=<IBM_CLOUD_API_KEY>" \
  "https://iam.cloud.ibm.com/identity/token"
```

2. Query `/v1/accounts/<ORG_GUID>/users`:
```bash
curl -X GET \
https://user-management.cloud.ibm.com/v1/accounts/<ORG_GUID>/users \
  -H 'Authorization: Bearer <IAM_ACCESS_TOKEN_FROM_STEP_ABOVE>
```

This call results in response:
> {“errors”:[{“code”:9999,“message”:“Current user does not have access to team directory.“,”more_info”:“”}]}%


However, when changing the API version to `/v2` it seems to work - i'm getting some response.


Can we get it fixed by making `terraform-provider-ibm` make use of `/v2` API in this call?

This is a major blocker for us. If there is a way of getting around this issue by altering our permissions in IBM Cloud, i'd be interested to know...

**Comment by mzmudziak** [comment] 2019-10-02 10:28
@hkantare Hey.. Not sure if you are the right person to notify, but can you please take a look at this issue, and maybe try to help? Not sure if there is any workaround to this, but this makes unable to perform any actions using the provider that require the account data source.

**Comment by mbirch-ca** [comment] 2019-11-06 20:21
As follow-up to [this comment](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/671#issuecomment-537431944) , I found the same behaviour and got IBM Cloud support to confirm that the change is required given the access model in the older version.  (Or [modify the IAM setting](https://cloud.ibm.com/docs/iam?topic=iam-userlistview) to have unrestricted user visibility.)

**Comment by mbirch-ca** [comment] 2019-11-07 01:14
Based on the error, it would appear that the issue exists on [line 66 of data_source_ibm_account.go](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/data_source_ibm_account.go#L66)

Just not sure what to change is needed from "accountv1Client"

**Comment by umarali-nagoor** [comment] 2019-11-22 11:17
Hi all,
             Tried to reproduce the issue but the issue is not reproducible
            
              Vesrions : 

                         Terraform                         :    0.11.14
           
                         Terraform-provider-ibm  :    0.19.0

            Terraform .tf files code snippet is : 

                        data "ibm_org" "org" {
                                org = "example.org"
                        }

                       data "ibm_account" "account" {
                                org_guid = "${data.ibm_org.org.id}"
                        }

                       output "id" {
                                value = "${data.ibm_account.account.id}"
                       }

                       output "users" {
                               value = "${data.ibm_account.account.account_users}"
                       }


  Steps executed : 

                      For initial phase
 
                              terraform init

                     For planning phase

                             terraform plan

                    For apply phase

                            terraform apply

Result : 

                   Outputs:

                      id = xyz..

                    users = [
                   {
                       email = abc@example.com,
                       id = 123,
                      role = MEMBER,
                     state = PENDING
                   },
                  {
                   email =xyz@example.com,
                   id = 456,
                   role = MEMBER,
                  state = PENDING
                 },
                {
                 email =abc@example.com,
                 id =678,
                role = MEMBER,
                state = PENDING
                },
               {
                   email = abc@in.ibm.com,
                   id = 897,
                   role = MEMBER,
                   state = ACTIVE
              },
             {
                email = xyz@in.ibm.com,
                 id = 534,
                 role = PRIMARY_OWNER,
                 state = ACTIVE
            }
     ]

Observed behaviour : 

             Data source "ibm_account" details are retrieved as expected

Please try to reproduce the issue once and provide the corresponding versions of sdk, terraform and terraform-provider-ibm being used

**Comment by hkantare** [comment] 2019-11-25 08:11
The ibm_account is based on mccp endpoint but where as the curl request you tried is user management endpoint https://github.com/IBM-Cloud/terraform-provider-ibm/issues/671#issuecomment-537431944.

We are in development phase to support user management endpoint . We need to come up with new datasource to list users in account https://cloud.ibm.com/apidocs/user-management#get-users

**Comment by jjasghar** [comment] 2020-06-17 17:09
I would like to say this error popped up for @mpetersen and I today.

We discovered that this option (https://cloud.ibm.com/iam/settings):
![image](https://user-images.githubusercontent.com/810824/84928025-54f14300-b093-11ea-8a31-b2e48e330244.png)
was turned **ON** due to a miss understanding.
We turned it off and everything started working for us.

**Comment by hkantare** [comment] 2021-12-08 07:58
closing the issue due to no recent activity. Please feel free to open new issue

**Closed by hkantare** 2021-12-08 07:58 UTC
