### ISSUE TITLE
VPC Gen2 subnet not attaching to public gateway

### ISSUE THREAD

**Issue by argeiger** [IBM-Cloud/terraform-provider-ibm#1626] opened 2020-07-02 15:44 UTC
### Terraform Version
Terraform v0.12.24
+ provider.ibm v1.8.1

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_is_subnet

### Terraform Configuration Files
Initial Apply without Public Gateway
```
  # module.vpc.ibm_is_subnet.subnets["us-south-1-subnet"] will be created
  + resource "ibm_is_subnet" "subnets" {
      + available_ipv4_address_count = (known after apply)
      + id                           = (known after apply)
      + ip_version                   = "ipv4"
      + ipv4_cidr_block              = "172.21.0.0/24"
      + ipv6_cidr_block              = (known after apply)
      + name                         = "us-south-1-subnet"
      + network_acl                  = (known after apply)
      + resource_controller_url      = (known after apply)
      + resource_crn                 = (known after apply)
      + resource_group               = "e1d6e82017384baba3ecfb33f3f6a12c"
      + resource_group_name          = (known after apply)
      + resource_name                = (known after apply)
      + resource_status              = (known after apply)
      + status                       = (known after apply)
      + total_ipv4_address_count     = (known after apply)
      + vpc                          = (known after apply)
      + zone                         = "us-south-1"

      + timeouts {
          + create = "90m"
          + delete = "30m"
        }
    }
```

Apply after initial apply:
```
  # module.vpc.ibm_is_subnet.subnets["us-south-1-subnet"] will be updated in-place
  ~ resource "ibm_is_subnet" "subnets" {
        id                       = "0717-574c7fff-9500-4742-af22-701558a49101"
        ip_version               = "ipv4"
        ipv4_cidr_block          = "172.21.0.0/24"
        name                     = "us-south-1-subnet"
        network_acl              = "r006-fca973f8-5c9f-4aa2-9dee-0956e02f92f0"
      + public_gateway           = "r006-59783469-2c70-486a-a724-cb649ffe6109"
        resource_controller_url  = "https://cloud.ibm.com/vpc-ext/network/subnets"
        resource_crn             = "crn:v1:bluemix:public:is:us-south-1:a/26a3d1a386bd2cc44df1997eb7ac0ef1::subnet:0717-574c7fff-9500-4742-af22-701558a49101"
        resource_group           = "e1d6e82017384baba3ecfb33f3f6a12c"
        resource_group_name      = "default"
        resource_name            = "us-south-1-subnet"
        resource_status          = "available"
        status                   = "available"
        total_ipv4_address_count = 256
        vpc                      = "r006-6d539e82-f10a-4926-948a-7d2eae1510ed"
        zone                     = "us-south-1"

        timeouts {
            create = "90m"
            delete = "30m"
        }
    }
```

### Expected Behavior
Expected the subnet to be attached to the public gateway

### Actual Behavior
The subnet was not attached

![image](https://user-images.githubusercontent.com/14077904/86379682-2493d200-bc59-11ea-8455-d3682c55d551.png)

### Steps to Reproduce
1. Creating the VPC resources without having the subnet attached to the gateway and apply plan
2. Add the public gateway to the resource and apply plan

**Comment by ileneruth** [comment] 2020-07-04 20:21
I'm seeing the same issue with gen 1.  I don't know go, but I _think_ the problem is in these blocks of resource_ibm_subnet.go where it's only handling empty gateway and not adding/changing.

```
if d.HasChange(isSubnetPublicGateway) {
		gw := d.Get(isSubnetPublicGateway).(string)
		if gw == "" {
			deleteSubnetPublicGatewayBindingOptions := &vpcclassicv1.DeleteSubnetPublicGatewayBindingOptions{
				ID: &id,
			}
			response, err := sess.DeleteSubnetPublicGatewayBinding(deleteSubnetPublicGatewayBindingOptions)
			if err != nil {
				return fmt.Errorf("Error Detaching public gateway attached to the subnet : %s\n%s", err, response)
			}
			_, err = isWaitForClassicSubnetAvailable(sess, d.Id(), d.Timeout(schema.TimeoutDelete))
			if err != nil {
				return err
			}
			updateSubnetOptions.PublicGateway = &vpcclassicv1.PublicGatewayIdentity{
				ID: &gw,
			}
			hasChanged = true
		}
	}
```

**Comment by hkantare** [comment] 2020-07-06 04:23
We are looking into this issue..

**Comment by hkantare** [comment] 2020-07-23 06:49
Fixed in latest release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.9.0

**Closed** 2020-08-18 10:21 UTC
