### ISSUE TITLE
ibm_cos_bucket doesn't have the right value for `s3_endpoint_public` when `endpoint_type` is set to private

### ISSUE THREAD

**Issue by akocbek** [IBM-Cloud/terraform-provider-ibm#5404] opened 2024-05-31 18:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

   
  
  
When we create `ibm_cos_bucket` resource using ibm provider and we set `endpoint_type` to private then `s3_endpoint_public` has `private` endpoint instead of `public`.

```hcl
"s3_endpoint_direct" = "s3.direct.us-south.cloud-object-storage.appdomain.cloud"
"s3_endpoint_private" = "s3.private.us-south.cloud-object-storage.appdomain.cloud"
"s3_endpoint_public" = "s3.private.us-south.cloud-object-storage.appdomain.cloud"
```

### Affected Resource(s)

* ibm_cos_bucket

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ibm_resource_group" "resource_group" {
  name     = "a-test-rg"
}


resource "ibm_resource_instance" "cos_instance" {
  name              = "a-test-cos-instance"
  resource_group_id = resource.ibm_resource_group.resource_group.id
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
}

resource "ibm_cos_bucket" "cos_bucket_test" {
  resource_instance_id  =  resource.ibm_resource_instance.cos_instance.id
  bucket_name           = "a-test-cos-bucket"
  region_location       = "us-south"
  endpoint_type = "private"
}

output ibm_cos_bucket {
    value = ibm_cos_bucket.cos_bucket_test
}
```

### Debug Output

https://gist.github.com/akocbek/4e181df0042eb670f158461e55c24f4e

### Expected Behavior

`s3_endpoint_public` output variable should have public endpoint, when `endpoint_type` input variable is set to `private`

### Actual Behavior

`s3_endpoint_public` output variable has private endpoint, when `endpoint_type` input variable is set to `private`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by IBM-diksha** [comment] 2024-06-04 14:54
@akocbek  We are looking into this.
Thank you.

**Comment by IBM-Deeksha** [comment] 2024-06-06 12:37
@akocbek 
We have investigated the issue and have identified the root cause. 
Our team is currently working on a solution. We'll keep you updated on our progress.

**Comment by IBM-Deeksha** [comment] 2024-06-18 06:55
Delivered fix. Thank you for reporting.

**Comment by IBM-diksha** [comment] 2024-07-01 05:49
Closing the Issue as the fix has been delivered.
Thank you.

**Closed by IBM-diksha** 2024-07-01 05:49 UTC
Labels: service/Object Storage, service/Resource Management

**Comment by akocbek** [comment] 2024-07-01 08:12
@IBM-Deeksha  thank you
