### ISSUE TITLE
"Console Administrator" role keeps being remapped to "VirtualServerConsoleAdmin"

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/terraform-provider-ibm#2487] opened 2021-04-08 23:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

- Terraform v0.14.10
- provider registry.terraform.io/ibm-cloud/ibm v1.23.1

### Affected Resource(s)

* ibm_iam_access_group_policy

### Terraform Configuration Files

```hcl
resource "ibm_iam_access_group_policy" "kvm_for_ops" {
  access_group_id = ibm_iam_access_group.group["ops"].id
  roles           = ["Console Administrator"]

  # Add role based on resource group
  resources {
    service           = "is"
    resource_group_id = ibm_resource_group.group.id
  }
}
```

### Expected Behavior

Applying twice should do nothing

### Actual Behavior

When you apply the second time, it changes the value.

```hcl
Terraform will perform the following actions:

  # ibm_iam_access_group_policy.kvm_for_ops will be updated in-place
  ~ resource "ibm_iam_access_group_policy" "kvm_for_ops" {
        id                 = "xxx"
      ~ roles              = [
          - "VirtualServerConsoleAdmin",
          + "Console Administrator",
        ]
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If I look into the state after the first apply `Console Administrator` is changed to `VirtualServerConsoleAdmin`.

```json
{
      "mode": "managed",
      "type": "ibm_iam_access_group_policy",
      "name": "kvm_for_ops",
      "provider": "provider[\"registry.terraform.io/ibm-cloud/ibm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "access_group_id": "xxx",
            "account_management": false,
            "id": "xxx",
            "resources": [
              {
                "attributes": null,
                "region": "",
                "resource": "",
                "resource_group_id": "xxx",
                "resource_instance_id": "",
                "resource_type": "",
                "service": "is"
              }
            ],
            "roles": [
              "VirtualServerConsoleAdmin"
            ],
            "tags": null,
            "version": "1-996cd465f6869ebbd8b82107741e639c"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "ibm_iam_access_group.group",
            "ibm_resource_group.group"
          ]
        }
      ]
    }
```

I tried using "VirtualServerConsoleAdmin" in the first place but there it complains `Error: RoleDoesnotExist: VirtualServerConsoleAdmin was not found. Valid roles are IP Spoofing Operator, Console Administrator, Viewer, Administrator, Operator, Editor".`

### Steps to Reproduce

`terraform apply` twice

**Comment by guicabr** [comment] 2021-06-24 20:20
Looking into this. I checked the `v2/roles?service_name=is` and saw that there is no `VirtualServerConsoleAdmin` role, but that string is part of the CRN for the "Console Administrator" role.
```
        {
            "crn": "crn:v1:bluemix:public:is::::serviceRole:VirtualServerConsoleAdmin",
            "display_name": "Console Administrator",
            "description": "As a console administrator, you can access the virtual server instance console., This role only provides console access and must be combined with another role that has operator access to the virtual server such as Operator, Editor or Administrator.",
            "actions": [
                "is.instance.instance.console"
            ]
        },
```

**Comment by guicabr** [comment] 2021-06-25 16:50
Was able to reproduce with following Terraform config:

```
resource "ibm_iam_access_group" "accgrp" {
  name        = "test"
  description = "New access group"
}

data "ibm_resource_group" "defaultgroup" {
  is_default = "true"
}

resource "ibm_iam_access_group_policy" "kvm_for_ops" {
  access_group_id = ibm_iam_access_group.accgrp.id
  roles           = ["Console Administrator"]

  resources {
    service           = "is"
    resource_group_id = data.ibm_resource_group.defaultgroup.id
  }
}
```
After using Policy Management API to look at the policy, came to see that when we simply create the Access Group Policy we are already incorrectly adding  the "VirtualServerConsoleAdmin" display name as opposed to "Console Administrator" which was specified.
```
    "roles": [
        {
            "role_id": "crn:v1:bluemix:public:is::::serviceRole:VirtualServerConsoleAdmin",
            "display_name": "VirtualServerConsoleAdmin",
            "description": "VirtualServerConsoleAdmin"
        }
```

**Comment by guicabr** [comment] 2021-06-25 18:06
* Issue seems to be happening only with `is` service and when custom service roles are used in the Access Group policy. I am not able to reproduce when using "Reader" role for example (ex. correct role CRN, display name and description). 
* This is also not reproducible with say `cloud-object-storage` and using a custom service role (ex Object Reader). Thus, issue is not solely because of the use of custom service role.

**Comment by guicabr** [comment] 2021-07-02 15:20
Fix for issue has been delivered in Policy Management API. Will update whenever this becomes available in Production environment.

**Comment by kavya498** [comment] 2021-11-08 15:14
@l2fprod ,
Looks like this is been fixed by API team..
Can you check on this and let us know so that we can close this issue..

Thanks

**Comment by kavya498** [comment] 2021-11-16 06:57
Closing this issue thanks..

**Closed by kavya498** 2021-11-16 06:57 UTC
Labels: IAMPAP
