### ISSUE TITLE
Access denied by subnets retrieving over terraform

### ISSUE THREAD

**Issue by nachevn** [IBM-Cloud/terraform-provider-ibm#269] opened 2018-06-04 12:59 UTC
Hi all,

I'm getting an error by the retrieving of the subnets via terraform, created by another user, although I'm able to see them over the cloud provider UI dashboard.

```
2018-05-30T09:00:13.638+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:13 [DEBUG] Request URL:  GET https://api.softlayer.com/rest/v3/SoftLayer_Network_Subnet/1234567.json
2018-05-30T09:00:13.638+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:13 [DEBUG] Parameters:
2018-05-30T09:00:13.638+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:13 [DEBUG] Request URL:  GET https://api.softlayer.com/rest/v3/SoftLayer_Network_Subnet/1765432.json
2018-05-30T09:00:13.638+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:13 [DEBUG] Parameters:
2018-05-30T09:00:14.355+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:14 [DEBUG] Response:  {"error":"Access Denied. ","code":"SoftLayer_Exception_Public"}
2018/05/30 09:00:14 [ERROR] root: eval: *terraform.EvalRefresh, err: ibm_subnet.public_subnet: Error retrieving subnet: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
2018/05/30 09:00:14 [ERROR] root: eval: *terraform.EvalSequence, err: ibm_subnet.public_subnet: Error retrieving subnet: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
2018/05/30 09:00:14 [TRACE] [walkRefresh] Exiting eval tree: ibm_subnet.public_subnet
2018/05/30 09:00:14 [ERROR] root: eval: *terraform.EvalRefresh, err: ibm_subnet.private_subnet: Error retrieving subnet: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
2018/05/30 09:00:14 [ERROR] root: eval: *terraform.EvalSequence, err: ibm_subnet.private_subnet: Error retrieving subnet: SoftLayer_Exception_Public: Access Denied.  (HTTP 401)
2018/05/30 09:00:14 [TRACE] [walkRefresh] Exiting eval tree: ibm_subnet.private_subnet
2018-05-30T09:00:14.358+0200 [DEBUG] plugin.terraform-provider-ibm_v0.8.0: 2018/05/30 09:00:14 [DEBUG] Response:  {"error":"Access Denied. ","code":"SoftLayer_Exception_Public"}
2018/05/30 09:00:14 [TRACE] dag/walk: upstream errored, not walking "ibm_container_cluster.toolchain_applications"
2018/05/30 09:00:14 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
```
Here is the part of the terraform script used by me:
```
variable "ibm_bmx_api_key" {}
variable "ibm_bmx_account_guid" {}
variable "ibm_bmx_region" {}

variable "ibm_sl_username" {}
variable "ibm_sl_api_key" {}
variable "kubernetes_cluster_name" {}
variable "private_vlan_id" {}
variable "public_vlan_id" {}

....

# Configure the IBM Cloud Provider
provider "ibm" {
  version            = "0.8.0"
  bluemix_api_key    = "${var.ibm_bmx_api_key}"
  region             = "${var.ibm_bmx_region}"
  softlayer_username = "${var.ibm_sl_username}"
  softlayer_api_key  = "${var.ibm_sl_api_key}"
}
...
# Creation of the private subnet
resource "ibm_subnet" "private_subnet" {
  type       = "Portable"
  private    = true
  ip_version = 4
  capacity   = 16
  vlan_id    = "${var.private_vlan_id}"
  notes      = "private_subnet"
}

# Creation of the public subnet
resource "ibm_subnet" "public_subnet" {
  type       = "Portable"
  private    = false
  ip_version = 4
  capacity   = 16
  vlan_id    = "${var.public_vlan_id}"
  notes      = "public_subnet"
}

# Creation of the cluster 
resource "ibm_container_cluster" "toolchain_applications" {
  name            = "${var.kubernetes_cluster_name}"
  public_vlan_id  = "${var.public_vlan_id}"                                                       
  private_vlan_id = "${var.private_vlan_id}"
  subnet_id       = ["${ibm_subnet.private_subnet.id}", "${ibm_subnet.public_subnet.id}"]
....
```

The public and the private vlan IDs are defined in a *.tfvars file.

Terraform version 0.11.7
IBM provider version: 0.8.0

**Comment by sakshiag** [comment] 2018-06-04 13:08
@nachevn : I see you are getting access denied.. I hope Softlayer username  and api key is correctly set.
Can you try to access this url in the browser https://api.softlayer.com/rest/v3/SoftLayer_Network_Subnet/1765432.json and provide the same username and api key you are using for terraform and paste the output.

**Comment by nachevn** [comment] 2018-06-04 13:22
@sakshiag: Here is the output:

```
{
  "broadcastAddress":"XX.XXX.XXX.15",
  "cidr":28,
  "gateway":"XX.XXX.XXX.1",
  "id":1765432,
  "isCustomerOwned":false,
  "isCustomerRoutable":false,
  "modifyDate":"2018-05-30T01:31:26-06:00",
  "netmask":"255.255.255.240",
  "networkIdentifier":"XX.XXX.XXX.0",
  "networkVlanId":2345678,
  "note":"private_subnet",
  "sortOrder":"2",
  "subnetType":"SECONDARY_ON_VLAN",
  "totalIpAddresses":"16",
  "usableIpAddressCount":"13",
  "version":4
}
```

**Comment by sakshiag** [comment] 2018-06-05 06:55
@nachevn : We are not able to reproduce it.. In the description you have mentioned you are trying to retrieve the subnet created by other user. Can you provide the proper steps to recreate the issue.

Please enable the log trace and provide the complete logs in the issue.

**Comment by sakshiag** [comment] 2018-06-12 10:15
@nachevn : you are still facing this issue.. ?

**Comment by hkantare** [comment] 2018-12-20 08:07
closing the issue..no updates from long time

**Closed by hkantare** 2018-12-20 08:07 UTC
