### ISSUE TITLE
[Terraform v0.12.0-alpha2] Failed to instantiate provider "ibm" to obtain schema...

### ISSUE THREAD

**Issue by giorgioazzinnaro** [IBM-Cloud/terraform-provider-ibm#422] opened 2018-11-19 13:21 UTC
### Terraform Version

`Terraform v0.12.0-alpha2`

I get this error when using the new *alpha* release of Terraform, v0.12:

```
Error: Failed to instantiate provider "ibm" to obtain schema: Incompatible API version with plugin. Plugin ver
sion: 4, Client versions: [5]
```

### Steps to Reproduce
1. Download [Terraform v0.12](https://releases.hashicorp.com/terraform/0.12.0-alpha2/)
2. `terraform plan` of a workspace making use of this provider

### References
According to [Terraform docs](https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers) a new version of the plugin SDK would provide a compatibility layer for the new protocol.

I'll attempt a build against a more recent version of this SDK and report back with a PR hopefully!

**Comment by hlarubi** [comment] 2019-05-25 18:05
Hi,

I updated to Terraform 0.12 and still seeing the issue.

Relevant versions:
$ terraform version
Terraform v0.12.0
+ provider.ibm (unversioned)

Here is the provider version:
2019/05/25 10:58:30 IBM Cloud Provider version 0.16.1  
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically

Running "terraform plan" causes the following errors:
Error: Failed to instantiate provider "ibm" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

Could you please let me know what I'm missing here?

Thanks!

**Comment by davetropeano** [comment] 2019-05-26 04:32
The IBM Cloud provider for Terraform does not support v0.12 yet. We will make an announcement when 0.12 is formally supported as there are many changes in this release of Terraform.

As for the issue of seeing `providet.ibm (unversioned)` when you do a `terraform version`... this can be caused based on the location of the IBM Cloud plugin. With terraform 0.11.x placing the plugin in `.terraform.d/plugins` displays the version properly.

**Comment by iambiff** [comment] 2019-06-05 20:27
I had a similar problem with Terraform v0.12 (the latest) against the latest IBM Cloud provider.  I removed my v0.12 version and downloaded v0.11.14:  https://releases.hashicorp.com/terraform/  for Mac and unzipped it into a directory in my PATH and now things are working.

**Comment by hlarubi** [comment] 2019-06-06 14:31
Thanks! That’s exactly how I got back up and running also. Looking forward to 0.12 support.

**Comment by Zman94** [comment] 2019-10-01 14:52
I see a requirement on the README for terraform version > 0.10.1. Is terraform 0.12.x not supported still? I'm having the same issue as above

**Comment by jboneu** [comment] 2019-10-16 02:47
Same here, still carrying with the same issue, it have almost a year since this have been reported, and it is impossible to use terraform with ibm infrastructure. all the other big providers obviusly work fine. Big miss for ibm.

**Comment by hkantare** [comment] 2019-11-18 11:34
Duplicate of https://github.com/IBM-Cloud/terraform-provider-ibm/issues/594

**Closed** 2020-04-17 09:25 UTC
Labels: duplicate
