### ISSUE TITLE
datasource scehamtics output values fails with error for tf 12 list variables

### ISSUE THREAD

**Issue by Praveengostu** [IBM-Cloud/terraform-provider-ibm#1345] opened 2020-04-22 05:18 UTC
datasource scehamtics output values fails with error for tf 12 list variables
```
data.ibm_schematics_workspace.vpc_workspace: Refreshing state...
data.ibm_schematics_output.vpc_workspace: Refreshing state...
Warning: "bluemix_api_key": [DEPRECATED] This field is deprecated please use ibmcloud_api_key
Error: Error while retreiving outputs of workspace: json: cannot unmarshal array into Go struct field OutputValues.output_values.type of type string
  on main.tf line 5, in data "ibm_schematics_output" "vpc_workspace":
   5: data "ibm_schematics_output" "vpc_workspace" {
```

**Comment by hkantare** [comment] 2020-05-04 10:19
Fixed in latest releases
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.1
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.5.0

**Comment by Anil-CM** [comment] 2020-07-22 10:54
The issue is been fixed, hence closing it.

**Closed by Anil-CM** 2020-07-22 10:54 UTC
