### ISSUE TITLE
SSH Key not copied to the server

### ISSUE THREAD

**Issue by lucaswxp** [IBM-Cloud/terraform-provider-ibm#370] opened 2018-09-25 22:31 UTC
### Terraform Version
v0.11.08

### Affected Resource(s)
- ibm_compute_vm_instance

### Terraform Configuration Files
no config file, default config

### Expected Behavior
After creating a instance with ssh key ids specified, I was expecting to be able to login with that key.

### Actual Behavior
The key was never copied to the server. If I login using password I can see that  ~/.ssh/authorized_keys is empty

### Steps to Reproduce
```hcl
# Create a virtual server with the SSH key
resource "ibm_compute_vm_instance" "36274eef-2664-4ea8-98af-908e39d5a364" {
  hostname          = "36274eef-2664-4ea8-98af-908e39d5a364.xxx.com.br"
  domain            = "xxxx.com.br"
  ssh_key_ids       = [1211481]
  os_reference_code = "UBUNTU_16_64"
  datacenter        = "sao01"
  network_speed     = 100
  flavor_key_name   = "B1_1X2X25"
  local_disk        = false
  public_security_group_ids = [880093]
  private_security_group_ids = [880093]
}
```

Outputs:
```
 ibm_compute_vm_instance.239813b8-369c-4087-b3d1-ccb9ffdc02b9: Creating...
   block_storage_ids.#:               "" => "<computed>"
   cores:                             "" => "<computed>"
   datacenter:                        "" => "sao01"
   disks.#:                           "" => "<computed>"
   domain:                            "" => "reduza.com.br"
   file_storage_ids.#:                "" => "<computed>"
   flavor_key_name:                   "" => "B1_1X2X25"
   hostname:                          "" => "239813b8-369c-4087-b3d1-ccb9ffdc02b9.xxx.com.br"
   hourly_billing:                    "" => "true"
   ip_address_id:                     "" => "<computed>"
   ip_address_id_private:             "" => "<computed>"
   ipv4_address:                      "" => "<computed>"
   ipv4_address_private:              "" => "<computed>"
   ipv6_address:                      "" => "<computed>"
   ipv6_address_id:                   "" => "<computed>"
   ipv6_enabled:                      "" => "false"
   ipv6_static_enabled:               "" => "false"
   local_disk:                        "" => "false"
   memory:                            "" => "<computed>"
   network_speed:                     "" => "100"
   os_reference_code:                 "" => "CENTOS_6_64"
   private_interface_id:              "" => "<computed>"
   private_network_only:              "" => "false"
   private_security_group_ids.#:      "" => "1"
   private_security_group_ids.880093: "" => "880093"
   private_subnet:                    "" => "<computed>"
   private_subnet_id:                 "" => "<computed>"
   private_vlan_id:                   "" => "<computed>"
   public_bandwidth_limited:          "" => "<computed>"
   public_bandwidth_unlimited:        "" => "false"
   public_interface_id:               "" => "<computed>"
   public_ipv6_subnet:                "" => "<computed>"
   public_ipv6_subnet_id:             "" => "<computed>"
   public_security_group_ids.#:       "" => "1"
   public_security_group_ids.880093:  "" => "880093"
   public_subnet:                     "" => "<computed>"
   public_subnet_id:                  "" => "<computed>"
   public_vlan_id:                    "" => "<computed>"
   secondary_ip_addresses.#:          "" => "<computed>"
   ssh_key_ids.#:                     "" => "1"
   ssh_key_ids.1211481:               "" => "1211481"
   wait_time_minutes:                 "" => "90"
```
You can see in the output that "ssh_key_ids" is set.

Is there anyway I can output the root password so I can login to the machine programatically until this bug gets fixed?

**Comment by hkantare** [comment] 2018-09-26 05:05
Hi we are not able to reproduce the issue we were successfully logged into vm  using private key....
```
# Create a new ssh key 
resource "ibm_compute_ssh_key" "ssh_key" {
    label = "${var.ssh_label}"
    notes = "for public vlan test"
    public_key = "${var.ssh_public_key}"
}

resource "ibm_compute_vm_instance" "36274eef-2664-4ea8-98af-908e39d5a364" {
  hostname          = "36274eef-2664-4ea8-98af-908e39d5a364.xxx.com.br"
  domain            = "xxxx.com.br"
  ssh_key_ids       = ["${ibm_compute_ssh_key.ssh_key.id}"]
  os_reference_code = "UBUNTU_16_64"
  datacenter        = "sao01"
  network_speed     = 100
  flavor_key_name   = "B1_1X2X25"
  local_disk        = false
}
```

I tried with above configuration..
```
id = 1233791
  fingerprint = 1c:c6:ca:b7:6f:4f:0d:20:ec:40:d0:90:27:47:ae:53
  label = ssh_key_vlan
  notes = for public vlan test
  public_key = XXXXXX
ibm_compute_vm_instance.36274eef-2664-4ea8-98af-908e39d5a364:
  id = 62256355
  block_storage_ids.# = 0
  cores = 1
  datacenter = sao01
  dedicated_acct_host_only = false
  disks.# = 0
  domain = xxxx.com.br
  file_storage_ids.# = 0
  flavor_key_name = B1_1X2X25
  hostname = 36274eef-2664-4ea8-98af-908e39d5a364.xxx.com.br
  hourly_billing = true
  ip_address_id = 120265721
  ip_address_id_private = 120265781
  ipv4_address = 169.57.208.178
  ipv4_address_private = 10.151.49.72
  ipv6_enabled = false
  ipv6_static_enabled = false
  local_disk = false
  memory = 2048
  network_speed = 100
  notes = 
  os_reference_code = UBUNTU_16_64
  private_interface_id = 35922829
  private_network_only = false
  private_security_group_ids.# = 0
  private_subnet = 10.151.49.64/26
  private_subnet_id = 1845928
  private_vlan_id = 2450049
  public_bandwidth_unlimited = false
  public_interface_id = 35922831
  public_security_group_ids.# = 0
  public_subnet = 169.57.208.176/28
  public_subnet_id = 1849985
  public_vlan_id = 2450047
  secondary_ip_addresses.# = 0
  ssh_key_ids.# = 1
  ssh_key_ids.1233791 = 1233791
  wait_time_minutes = 90

Harinis-MacBook-Pro:ibm-network-vlan hkantare$ ssh root@169.57.208.178
The authenticity of host '169.57.208.178 (169.57.208.178)' can't be established.
ECDSA key fingerprint is SHA256:4Z636oBoR17IsWEkGWnvD85puPzN3Sg8WBOi67yy8Js.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '169.57.208.178' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-133-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.
```

**Comment by lucaswxp** [comment] 2018-09-26 19:40
@hkantare Thank you!
Weird.. now it's working, and I didn't change anything.
Sorry to take your time.

**Comment by lucaswxp** [comment] 2018-09-27 16:47
So, this started happening again, after a couple successful attempts...

```
 ibm_compute_ssh_key.462b6127-945a-4675-b4bc-ccd379654144: Creating...
   fingerprint: "" => "<computed>"
   label:       "" => "key-462b6127-945a-4675-b4bc-ccd379654144"
   public_key:  "" => "ssh-rsa XXXX lucaswxp@imhuman\n"
 ibm_compute_ssh_key.462b6127-945a-4675-b4bc-ccd379654144: Creation complete after 1s (ID: 1246093)
 ibm_compute_vm_instance.462b6127-945a-4675-b4bc-ccd379654144: Creating...
   block_storage_ids.#:               "" => "<computed>"
   cores:                             "" => "<computed>"
   datacenter:                        "" => "sao01"
   disks.#:                           "" => "<computed>"
   domain:                            "" => "xxx.com.br"
   file_storage_ids.#:                "" => "<computed>"
   flavor_key_name:                   "" => "B1_8X32X25"
   hostname:                          "" => "462b6127-945a-4675-b4bc-ccd379654144.xx.com.br"
   hourly_billing:                    "" => "true"
   ip_address_id:                     "" => "<computed>"
   ip_address_id_private:             "" => "<computed>"
   ipv4_address:                      "" => "<computed>"
   ipv4_address_private:              "" => "<computed>"
   ipv6_address:                      "" => "<computed>"
   ipv6_address_id:                   "" => "<computed>"
   ipv6_enabled:                      "" => "false"
   ipv6_static_enabled:               "" => "false"
   local_disk:                        "" => "false"
   memory:                            "" => "<computed>"
   network_speed:                     "" => "100"
   os_reference_code:                 "" => "UBUNTU_16_64"
   private_interface_id:              "" => "<computed>"
   private_network_only:              "" => "false"
   private_security_group_ids.#:      "" => "1"
   private_security_group_ids.880093: "" => "880093"
   private_subnet:                    "" => "<computed>"
   private_subnet_id:                 "" => "<computed>"
   private_vlan_id:                   "" => "<computed>"
   public_bandwidth_limited:          "" => "<computed>"
   public_bandwidth_unlimited:        "" => "false"
   public_interface_id:               "" => "<computed>"
   public_ipv6_subnet:                "" => "<computed>"
   public_ipv6_subnet_id:             "" => "<computed>"
   public_security_group_ids.#:       "" => "1"
   public_security_group_ids.880093:  "" => "880093"
   public_subnet:                     "" => "<computed>"
   public_subnet_id:                  "" => "<computed>"
   public_vlan_id:                    "" => "<computed>"
   secondary_ip_addresses.#:          "" => "<computed>"
   ssh_key_ids.#:                     "" => "1"
   ssh_key_ids.1246093:               "" => "1246093"
   wait_time_minutes:                 "" => "90"
```

Then I tried to login:
```
ssh root@169.57.186.43
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:WabAUamHd9xb9llq/Al5THYlygLEUmu3vC/ZvdPhVy4.
Please contact your system administrator.
Add correct host key in /home/lucaswxp/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/lucaswxp/.ssh/known_hosts:288
  remove with:
  ssh-keygen -f "/home/lucaswxp/.ssh/known_hosts" -R 169.57.186.43
ECDSA host key for 169.57.186.43 has changed and you have requested strict checking.
Host key verification failed.
lucaswxp@imhuman:~/reduza/deployment$   ssh-keygen -f "/home/lucaswxp/.ssh/known_hosts" -R 169.57.186.43
```
You can see the IP have been used before by me, so I had to remove it from known_hosts. Maybe this have something to do with the problem.. don't know...

Then I tried login:
```
lucaswxp@imhuman:~/reduza/depssh root@169.57.186.43
The authenticity of host '169.57.186.43 (169.57.186.43)' can't be established.
ECDSA key fingerprint is SHA256:WabAUamHd9xb9llq/Al5THYlygLEUmu3vC/ZvdPhVy4.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '169.57.186.43' (ECDSA) to the list of known hosts.
Received disconnect from 169.57.186.43 port 22:2: Too many authentication failures
Connection to 169.57.186.43 closed by remote host.
Connection to 169.57.186.43 closed.
```

Finally I had to login with password:
```
ssh -o "PreferredAuthentications password" root@169.57.186.43
```

Then I checked if the ssh was copied:
```
root@462b6127-945a-4675-b4bc-ccd379654144:~# cat ~/.ssh/authorized_keys
<empty>
```

Nothing...

Any ideas?

**Comment by lucaswxp** [comment] 2018-09-27 16:51
So... I created another server that wasn't in my "known_hosts" before and it worked!
Could the server have some kind of "cache" with the previous key?

1. Try creating a machine with a ssh key
2. Then delete this machine.
2. Try creating the machine again, with a ssh key (can be the same). Hopes to get the same IP than the previous one
4. Try to login with ssh key, should fail

**Comment by hkantare** [comment] 2018-09-28 06:27
Yeah even we faced same issue ..try creating a server and get the same IP of the previous one and when we do ssh using private key it fails with strict host chekcing, when we cleared the entry from known_hosts file it works properly..May be you need to check with softlayer support.

**Comment by hkantare** [comment] 2018-12-20 07:34
closing the issue. If issue still exists please reopen it.

**Closed by hkantare** 2018-12-20 07:34 UTC
