### ISSUE TITLE
CRITICAL : Unable to provision FREE ibm_container_cluster instance on bluemix

### ISSUE THREAD

**Issue by M-Rushabh** [IBM-Cloud/terraform-provider-ibm#497] opened 2019-01-28 07:26 UTC
Hi there,

Terraform Version
Terraform v0.11.7
IBM Cloud Provider version 0.14.1

Affected Resource(s)
ibm_container_cluster

### Terraform Configuration Files
resource "ibm_container_cluster" "testacc" {
  name = "rushabhclusterc"
  datacenter = "dal12"
  machine_type = "free"
  hardware = "shared"  
}
### Debug Output
2019/01/28 06:19:51 [TRACE] dag/walk: vertex "root", waiting for: "provider.ibm (close)"
2019/01/28 06:19:51 [TRACE] dag/walk: vertex "provider.ibm (close)", waiting for: "ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1"
2019/01/28 06:19:51 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1"
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalWriteState
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalIf
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalWriteState
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/01/28 06:19:55 [TRACE] root: eval: *terraform.EvalApplyPost
2019/01/28 06:19:55 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
 * ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1: Error waiting for initializing ingress hostname and secret: Error retrieving cluster: Get https://containers.bluemix.net/v1/clusters/b2faf18a5e5a4cd8bba7e2c3a4ad13b2?showResources=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019/01/28 06:19:55 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
 * ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1: Error waiting for initializing ingress hostname and secret: Error retrieving cluster: Get https://containers.bluemix.net/v1/clusters/b2faf18a5e5a4cd8bba7e2c3a4ad13b2?showResources=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2019/01/28 06:19:55 [TRACE] [walkApply] Exiting eval tree: ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1
2019/01/28 06:19:55 [TRACE] dag/walk: upstream errored, not walking "provider.ibm (close)"
2019/01/28 06:19:55 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/01/28 06:19:55 [TRACE] dag/walk: upstream errored, not walking "root"
2019/01/28 06:19:55 [TRACE] Preserving existing state lineage "3d569499-7678-6035-c75d-b8ac18743bcf"
2019/01/28 06:19:55 [DEBUG] plugin: waiting for all plugin processes to complete...
 Error: Error applying plan:
 1 error(s) occurred:
 * ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1: 1 error(s) occurred:
2019-01-28T06:19:55.101Z [DEBUG] plugin.terraform-provider-ibm: 2019/01/28 06:19:55 [ERR] plugin: plugin server: accept unix /tmp/plugin619801443: use of closed network connection
* ibm_container_cluster.bfast-resource-ord-Bluemix-cb-SXPRMD7-1-1: Error waiting for initializing ingress hostname and secret: Error retrieving cluster: Get https://containers.bluemix.net/v1/clusters/b2faf18a5e5a4cd8bba7e2c3a4ad13b2?showResources=true: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
 Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
 2019-01-28T06:19:55.114Z [DEBUG] plugin: plugin process exited: path=/go/bin/terraform-provider-ibm

### Expected Behavior
Should deploy successfull
### Actual Behavior
Created free cluster on bluemix portal but error in retrieving status for cluster while terraform apply.

**Comment by Praveengostu** [comment] 2019-01-28 16:49
Could you please try by increasing the BM_TIMEOUT or BLUEMIX_TIMEOUT. By default its 60 seconds.
export BM_TIMEOUT=300

**Comment by M-Rushabh** [comment] 2019-01-29 09:54
@Praveengostu 
mrushabh@oc3585655060 ~/go/bin $ ibmcloud config --list
Name                                  Value   
Color enabled                         -   
HTTP timeout (Second)                 300   
Trace                                 -   
User locale                           -   
Check CLI version enabled             false   
Collecting usage statistics enabled   true  


this is my config TimeOut is 300 but getting following error
ibm_container_cluster.testacc: Still creating... (2h3m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.testacc: 1 error(s) occurred:

* ibm_container_cluster.testacc: Error waiting for initializing ingress hostname and secret: timeout while waiting for state to become 'normal' (last state: 'provisioning', timeout: 1h30m0s)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by Praveengostu** [comment] 2019-01-29 15:38
Hi @M-Rushabh the `ibmcloud config --list` display the configuration of ibmcloud cli not the terraform.. For terraform configuration just execute the command `export BM_TIMEOUT=300` and then retry creating the free cluster

**Comment by M-Rushabh** [comment] 2019-01-31 04:57
@Praveengostu  this also failed for me
ibm_container_cluster.testacc: Still creating... (2h15m1s elapsed)
ibm_container_cluster.testacc: Still creating... (2h15m11s elapsed)
ibm_container_cluster.testacc: Still creating... (2h15m21s elapsed)
ibm_container_cluster.testacc: Still creating... (2h15m31s elapsed)
ibm_container_cluster.testacc: Still creating... (2h15m41s elapsed)
ibm_container_cluster.testacc: Still creating... (2h15m51s elapsed)
ibm_container_cluster.testacc: Still creating... (2h16m1s elapsed)
ibm_container_cluster.testacc: Still creating... (2h16m11s elapsed)
ibm_container_cluster.testacc: Still creating... (2h16m21s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* ibm_container_cluster.testacc: 1 error(s) occurred:

* ibm_container_cluster.testacc: Error waiting for initializing ingress hostname and secret: timeout while waiting for state to become 'normal' (last state: 'provisioning', timeout: 1h30m0s)

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


mrushabh@oc3585655060 ~/go/bin $ echo $BM_TIMEOUT
300

**Comment by Praveengostu** [comment] 2019-01-31 05:13
@M-Rushabh Now the issue is different, is the above issue occurs for free cluster you are creating?

**Comment by koundinya-ac** [comment] 2019-01-31 05:19
hi #M-Rushabh can you please try changing the cluster name and retry, could you please try with a shorter name for the cluster ?

**Comment by M-Rushabh** [comment] 2019-02-04 09:16
I have change the template to following :=
resource "ibm_container_cluster" "testacc" {
  name = "clus"
  datacenter = "dal12"
  machine_type = "free"
 region = "us-south"
  hardware = "shared"
  wait_time_minutes=1440 
}
Its getting created on bluemix portal with state Normal but however in terrform its showing still creating taking too much time:=

ibm_container_cluster.testacc: Still creating... (3h26m10s elapsed)
ibm_container_cluster.testacc: Still creating... (3h26m20s elapsed)
ibm_container_cluster.testacc: Still creating... (3h26m30s elapsed)
ibm_container_cluster.testacc: Still creating... (3h26m40s elapsed)
ibm_container_cluster.testacc: Still creating... (3h26m50s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m0s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m10s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m20s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m30s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m40s elapsed)
ibm_container_cluster.testacc: Still creating... (3h27m50s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m0s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m10s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m20s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m30s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m40s elapsed)
ibm_container_cluster.testacc: Still creating... (3h28m50s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m0s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m10s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m20s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m30s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m40s elapsed)
ibm_container_cluster.testacc: Still creating... (3h29m50s elapsed)
ibm_container_cluster.testacc: Still creating... (3h30m0s elapsed)

**Comment by Praveengostu** [comment] 2019-02-04 09:21
Hi @M-Rushabh Yep there is a hang state identified with terraform.. We had pushed the fix to public and will be available in next release

**Comment by typekpb** [comment] 2019-06-25 12:52
I'm affected as well. Any updates in the area?

**Comment by typekpb** [comment] 2019-06-28 19:56
well, no more the case for me. Once having exported `TF_LOG=TRACE` and `TF_LOG_PATH` env vars, not facing the issue any more (no idea whether it's related or not).

**Comment by hkantare** [comment] 2019-07-01 08:24
closing the issue

**Closed by hkantare** 2019-07-01 08:24 UTC
