### ISSUE TITLE
Thoughts about adding Workers to Container Cluster.

### ISSUE THREAD

**Issue by Freyert** [IBM-Cloud/terraform-provider-ibm#85] opened 2017-11-20 17:11 UTC
Currently there's no Cluster Worker resource and therefore no way to add Workers to a cluster the terraform way.

If we were to add a Cluster Worker resource, the current API for creating Container Clusters would not mesh well because it makes Clusters dependent on Workers, but a Cluster must be created before a Worker can be created.

The true relation is that a Worker Depends on a Cluster. That is:

```
Worker -> Cluster
and not
Cluster -> Worker
```

I recommend the deprecation of the `ibm_container_cluster.workers` property in favor of creating a resource property `ibm_container_worker.cluster` that indicates the cluster a worker belongs to.

---

Caveats:
* It appears the current implementation only allows you to have a single type of machine resource.
  * The [Cluster API](https://github.com/IBM-Bluemix/bluemix-go/blob/master/api/container/containerv1/clusters.go#L93-L103) seems to dictate the type of worker nodes that can be added to the cluster. _Not_ the [worker API](https://github.com/IBM-Bluemix/bluemix-go/blob/master/api/container/containerv1/workers.go#L62-L66). This eliminates the capability to use a variety of 
nodes in a single cluster.

I think it's still worthwhile to create a Worker resource, but it would be limited in scope to just re-factoring the code within the "cluster resource" that manages workers, to be in an external resource.

This way, in the future the resource would be able to support more complex semantics than are available now; such as many _types_ of workers per cluster.

**Comment by vkalangu** [comment] 2017-11-24 07:36
@Freyert Thanks....We will look into this soon

**Comment by ashishth09** [comment] 2017-12-07 06:57
Cluster API has changed now, particularly the worker, we are updating the SDK and then we will have look into it.

**Comment by Praveengostu** [comment] 2018-02-05 16:51
For the new worker resource, see if the below schema solves the purpose. Review this and let me know your feedback
Schema: map[string]*schema.Schema{
            "cluster": {
                Type:        schema.TypeString,
                Required:    true,
                ForceNew:    true,
                Description: "The cluster name or id",
            },
            "datacenter": {
                Type:     schema.TypeString,
                Required: true,
                ForceNew: true,
            },
            "isolation": {
                Type:     schema.TypeString,
                Required: true,
                ForceNew: true,
            },
            "machine_type": {
                Type:     schema.TypeString,
                Required: true,
                ForceNew: true,
           }
            "privateVlan": {
                Type:     schema.TypeString,
                Required: true,
                ForceNew: true,
            },
            "publicVlan": {
                Type:     schema.TypeString,
                Required: true,
                ForceNew: true,
            },

    "version": {

                   Type:     schema.TypeString,
                   Optional: true,
                   Computed: true,
               },
        },

**Comment by IBMRob** [comment] 2018-02-13 09:27
THis is something we would be looking to use, specifically with the new AZ support coming out so would need to specify different vlans and zones on each worker.

**Comment by Praveengostu** [comment] 2018-02-28 05:42
Currently the worker post request returns an empty body. So we will not be able to get the ID of the worker which is created using the post request. We will try to figure out an alternate way to get the worker id which is needed.

**Comment by Praveengostu** [comment] 2018-03-06 13:52
We are working with our API team to return a valid ID for the worker Post request which will help us to identify the respective worker that gets created with each post request. Will keep update here once the API team fixes it.

**Comment by msvechla** [comment] 2018-03-06 16:35
+1 for adding support for adding workers in terraform.
I did some local playground tests, see: https://github.com/IBM-Cloud/terraform-provider-ibm/pull/148/commits/b11a5e95339179d6abfebbefad96cc238ddf3fc1

Would be nice if this can be added in the future

**Comment by Praveengostu** [comment] 2018-03-16 04:17
@msvechla Thank you creating the first draft for adding worker. We had also developed a similar worker resource which we haven't pushed yet as it does not comply with the terraform life cycle.  The issue is the worker post request returns an empty body. So we will not be able  to get the ID of the worker which is created using the post request. The worker ID has be persisted to perform the terraform operation like read,refresh, show,destroy etc...  With the resource you created we can just do a apply with which we can create the worker but we can update,destroy or read the worker that is created using terraform.. We are already working with the API development team to get the worker ID from the post request. Let us know if you have any quieres

**Comment by msvechla** [comment] 2018-03-16 18:15
Thanks for your reply. I also noticed that the worker ID is needed to make this work smoothly. Glad to hear you are working on that!

**Comment by StevenYCChou** [comment] 2018-05-31 18:30
any update on this? I want to add worker into a cluster by terraform too.

Also, I'd like to add worker has its own VLAN setting (say most of my workers are on private VLAN only, but I want to add a edge node which has both public/private VLAN attached). will it get supported when you guys finish the development, @Praveengostu ?

**Comment by Praveengostu** [comment] 2018-06-01 07:37
@StevenYCChou We are still working with the API development team to get the worker ID from the post request to create workers. We will update this space once we finish our deveopment

**Comment by StevenYCChou** [comment] 2018-06-01 18:07
just wondering... do you have any timeline @Praveengostu ? want to see when I can use it in near term (say in 1-2 month).

**Comment by benjamink** [comment] 2018-06-04 18:05
In the meantime is there any good way to dynamically generate the `workers` list in the `ibm_container_cluster` resource based on `worker_num` & `kube_version`?

**Comment by Praveengostu** [comment] 2018-06-07 16:57
@StevenYCChou We have some dependency(https://github.com/IBM-Cloud/terraform-provider-ibm/issues/85#issuecomment-373598919) to release the worker resource. Will keep this issue updated once we have a ETA.

**Comment by Praveengostu** [comment] 2018-07-12 04:13
Hi, We had released the worker pools and zones with release
https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.11.0.
One can create additional workers in different zones using `ibm_container_worker_pool` and `ibm_container_worker_pool_zone_attachment` resources

**Comment by Praveengostu** [comment] 2018-07-31 09:08
@Freyert Can we close this issue?

**Closed** 2018-10-26 17:43 UTC
