### ISSUE TITLE
Terraform destroy fails while destroying "VPN Server Route".

### ISSUE THREAD

**Issue by rajatagarwal-ibm** [IBM-Cloud/terraform-provider-ibm#4585] opened 2023-05-23 08:15 UTC
I am using Terraform to create a client-to-site VPN and VPN server route. When I do terraform apply both are getting created successfully. 

But when I do terraform destroy the status of the Client to Site VPN changes from "stable" to "failed" - this happens while destroying the "VPN Server Route". 

**VPN Created successfully after Terraform Apply**
![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/108140212/0fe2d92e-7b0e-4453-9a75-2e2e6d91c4d4)

**VPN Routes created successfully.**
![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/108140212/3c801b97-c240-45c4-b7f9-db4c4a76cde6)

**When destroying resources - VPN status changed to "failed" and fails terraform destroys**
![image](https://github.com/IBM-Cloud/terraform-provider-ibm/assets/108140212/46112514-272a-45d9-a741-5b15bc45b348)

### Terraform CLI and Terraform IBM Provider Version

IBM provider version: 1.51.0
Terraform version: Terraform v1.4.6

### Affected Resource(s)

* ibm_is_vpn_server 
* ibm_is_vpn_server_route

### Terraform Configuration Files

code snippet

main.tf
```
# Client to Site VPN
resource "ibm_is_vpn_server" "vpn" {
  certificate_crn = var.server_cert_crn
  client_authentication {
    method            = var.client_auth_methods
    identity_provider = var.client_auth_methods == "username" ? "iam" : null
  }
  client_idle_timeout    = var.client_idle_timeout
  client_ip_pool         = var.client_ip_pool
  client_dns_server_ips  = var.client_dns_server_ips
  enable_split_tunneling = var.enable_split_tunneling
  name                   = var.vpn_gateway_name
  subnets                = local.subnet_ids
  resource_group         = var.resource_group_id
}

resource "ibm_is_vpn_server_route" "server_route" {
  depends_on = [
    resource.ibm_iam_access_group.cts_vpn_access_group
  ]
  for_each    = var.vpn_server_routes
  vpn_server  = ibm_is_vpn_server.vpn.vpn_server
  destination = each.value.destination
  action      = each.value.action
  name        = each.key
}
```

variables.tf
```
variable "vpn_server_routes" {
  type = map(object({
    destination = string
    action      = string
  }))
  description = "Map of server routes to be added to created VPN server."
  default = {
    "vpc-192" = {
      destination = "192.168.0.0/22"
      action      = "deliver"
    }
  }
}
```

### Debug Output

Timeout while deleting VPN Server Route
```
│ Error: [ERROR] VPNServer Route failed timeout while waiting for state to become 'deleted, failed' (last state: 'deleting', timeout: 10m0s)
}
```

### Panic Output

Trace Logs [client-to-site-vpn-module-test-logs-230504-052259.tar.gz](https://github.com/IBM-Cloud/terraform-provider-ibm/files/11541779/client-to-site-vpn-module-test-logs-230504-052259.tar.gz)

### Expected Behavior

Should have deleted VPN Server Route successfully without changing Client to Site VPN state to fail.

### Actual Behavior

Timed out destroying VPN server route and change Client to Site VPN state to fail.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ocofaigh** [comment] 2023-07-27 10:53
@ujjwal-ibm Any update on this issue? I am also able to reproduce it:
`Error: [ERROR] VPNServer Route failed timeout while waiting for state to become 'deleted, failed' (last state: 'deleting', timeout: 10m0s)`

Here are the trace logs from my destroy attempt:
[trace.log](https://github.com/IBM-Cloud/terraform-provider-ibm/files/12182436/trace.log)

**Comment by ocofaigh** [comment] 2023-07-28 09:16
I found the root cause to this. Terraform was destroying the auth policy before the VNP server route, and so the route deletion gets stuck. I'll update my code to ensure the deletion order is correct.
Since I didn't create this issue, I have no access to close it and @rajatagarwal-ibm is on leave for a few weeks

**Closed** 2023-07-28 12:45 UTC
Labels: service/VPC Infrastructure
