### ISSUE TITLE
Our customer want to use Terraform to Tag IKS cluster. Currently Terraform tagging option does not store tags in the Cloud service endpoints.  Can you provide us any roadmap to implement this Gap?

### ISSUE THREAD

**Issue by paribiswas** [IBM-Cloud/terraform-provider-ibm#680] opened 2019-08-06 13:12 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- ibm_compute_instance
- ibm_storage_file

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by van-ibm** [comment] 2019-08-22 12:02
This looks like a duplicate of #470

**Comment by kevinisninja** [comment] 2019-08-22 12:12
Just updating for clarification,

this behavior is something listed in the documentation here:
https://ibm-cloud.github.io/tf-ibm-docs/v0.17.2/r/container_cluster.html

The tags property also says that tags "are managed locally and not stored on the IBM Cloud service endpoint at this moment." 

<img width="893" alt="Screen Shot 2019-08-22 at 2 09 09 PM" src="https://user-images.githubusercontent.com/14169364/63513552-e0875b00-c4e6-11e9-9bee-07fc79122b6d.png">

We were looking for an estimate of when that will change and when we can expect these tags to apply to the cluster on IBM Cloud

**Comment by hkantare** [comment] 2019-08-23 06:27
We will be working and make available in next release

**Comment by hkantare** [comment] 2019-09-06 12:39
Fixed in https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v0.17.3

**Closed** 2019-10-30 08:24 UTC
